{"uuid": "3582ffff-33e4-49cd-a8d8-2141c2bd0eb5", "children": ["820c6948-3be3-4d92-921b-4778e0b54bac"], "befores": [{"name": "get_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Requested environment is not available\n\n", "trace": "  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/conftest.py\", line 70, in get_driver\n    browser = webdriver.Remote(command_executor=config[\"selenoid\"], desired_capabilities=capabilities)\n  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 266, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"/home/eduard/Desktop/homework/2021-2-QA-AUTO-PYTHON-VKGROUP-E-Schultz/hw-2-XDIST-and-Allure/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1636201474899, "stop": 1636201474901}], "start": 1636201474899, "stop": 1636201474941}